<a href="https://colab.research.google.com/github/rahulranjan0909/Assessment---Data-Scientist_/blob/master/Untitled11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [45]:
data=pd.read_csv("/content/ts_model_sample_data.csv")

In [47]:
data["InvoiceDate"]=pd.to_datetime(data["InvoiceDate"])

In [48]:
from types import MethodType
data["Description"]=data["Description"].fillna("mode")

In [49]:
data["Quantity"]=abs(data["Quantity"])

In [50]:
data["Customer ID"]=data["Customer ID"].fillna("mode")

In [51]:
data=data.dropna()

In [52]:
data.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [53]:
data.shape

(1067371, 8)

In [54]:
(318268-67076)/318268

0.7892467982957759

In [55]:
data["Total"]=data["Quantity"]*data["Price"]

In [56]:
data.set_index("InvoiceDate",inplace=True)

In [60]:
data["Day_of_week"]=data.index.weekday

In [64]:
data.head(20)

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country,Total,Day_of_week
InvoiceDate,,,,,,,,,
2009-12-01 07:45:00,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,6.95,13085.0,United Kingdom,83.40,1
2009-12-01 07:45:00,489434,79323P,PINK CHERRY LIGHTS,12,6.75,13085.0,United Kingdom,81.00,1
2009-12-01 07:45:00,489434,79323W,WHITE CHERRY LIGHTS,12,6.75,13085.0,United Kingdom,81.00,1
2009-12-01 07:45:00,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2.10,13085.0,United Kingdom,100.80,1
2009-12-01 07:45:00,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,1.25,13085.0,United Kingdom,30.00,1
2009-12-01 07:45:00,489434,22064,PINK DOUGHNUT TRINKET POT,24,1.65,13085.0,United Kingdom,39.60,1
2009-12-01 07:45:00,489434,21871,SAVE THE PLANET MUG,24,1.25,13085.0,United Kingdom,30.00,1
2009-12-01 07:45:00,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,5.95,13085.0,United Kingdom,59.50,1
2009-12-01 07:46:00,489435,22350,CAT BOWL,12,2.55,13085.0,United Kingdom,30.60,1
2009-12-01 07:46:00,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,3.75,13085.0,United Kingdom,45.00,1
2009-12-01 07:46:00,489435,22195,HEART MEASURING SPOONS LARGE,24,1.65,13085.0,United Kingdom,39.60,1
2009-12-01 07:46:00,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2.55,13085.0,United Kingdom,30.60,1
2009-12-01 09:06:00,489436,48173C,DOOR MAT BLACK FLOCK,10,5.95,13078.0,United Kingdom,59.50,1
2009-12-01 09:06:00,489436,21755,LOVE BUILDING BLOCK WORD,18,5.45,13078.0,United Kingdom,98.10,1
2009-12-01 09:06:00,489436,21754,HOME BUILDING BLOCK WORD,3,5.95,13078.0,United Kingdom,17.85,1
2009-12-01 09:06:00,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,1.69,13078.0,United Kingdom,27.04,1
2009-12-01 09:06:00,489436,22119,PEACE WOODEN BLOCK LETTERS,3,6.95,13078.0,United Kingdom,20.85,1
2009-12-01 09:06:00,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,1.45,13078.0,United Kingdom,17.40,1
2009-12-01 09:06:00,489436,22296,HEART IVORY TRELLIS LARGE,12,1.65,13078.0,United Kingdom,19.80,1
2009-12-01 09:06:00,489436,22295,HEART FILIGREE DOVE LARGE,12,1.65,13078.0,United Kingdom,19.80,1

In [42]:
data.groupby("Customer ID","")["Total"].sum().reset_index()

      Customer ID    Total
0         12346.0   804.90
1         12349.0  1292.67
2         12355.0   488.21
3         12358.0  1697.93
4         12359.0  2106.03
...           ...      ...
3362      18281.0   120.32
3363      18283.0   446.42
3364      18285.0   427.00
3365      18286.0  1404.43
3366      18287.0  1076.71

[3367 rows x 2 columns]